name: AutF2
version: "1.0"
license: "GPL-2.0-or-later"
date: 2026-03-17
description: |
    Computations for the automorphisms group of F2

authors:
    - name: Óscar Fernández Ayala
      url: https://osferay.github.io/

maintainers:
    - name: Óscar Fernández Ayala
      url: https://osferay.github.io/

GAP: ">= 4.13"

needed-pkgs:
    - name: "json"
      version: ">=2.2.2"
      url: "https://gap-packages.github.io/json/"

www: https://osferay.github.io/AutF2/
readme: README.md
packageinfo: https://osferay.github.io/AutF2/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/osferay/AutF2/releases/download/v1.0/AutF2-1.0.tar.gz

abstract: |

doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>FA26</span>]   <b class='BibAuthor'>Fernández Ayala, Ó.</b>,
     <i class='BibTitle'>AutF2, Computations for the automorphisms group of F2,
             Version 1.0</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://osferay.github.io/AutF2/">https://osferay.github.io/AutF2/</a></span>.
    </p>
    

bibtex: |
    @misc{ AutF2,
      author =           {Fern{\a'a}ndez Ayala, {\a'O}.},
      title =            {{AutF2}, {Computations for the automorphisms group of F2}, {V}ersion 1.0},
      month =            {Mar},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href                                      {https://osferay.github.io/AutF2/}
                          {\texttt{https://osferay.github.io/}\discretionary      {}{}{}\texttt{research/}\discretionary
                          {}{}{}\texttt{software/}\discretionary {}{}{}\texttt{autf2}}},
      printedkey =       {FA26}
    }

