#! @Description
#! Returns whether the word u is cyclicaly reduced or not.
#! @Arguments u.
DeclareProperty( "IsCyclicalyReducedWord", IsAssocWordWithInverse );
#! @Description
#! Returns whether the word v is a subword of u or not.
#! @Arguments u,v.
DeclareOperation( "IsSubword", [ IsAssocWordWithInverse, IsAssocWordWithInverse ] );
#! @Description
#! Returns whether the word v is a prefix of u or not.
#! @Arguments u,v.
DeclareOperation( "IsPrefix", [ IsAssocWordWithInverse, IsAssocWordWithInverse ] );
#! @Description
#! Returns whether the word v is a suffix of u or not.
#! @Arguments u,v.
DeclareOperation( "IsSuffix", [ IsAssocWordWithInverse, IsAssocWordWithInverse ] );
#! @Description
#! Returns a word $w$ and an integer $r$ such that $w^r=v$ and $r$ is maximal.
#! @Arguments v.
DeclareOperation( "RootFreeGroup", [ IsAssocWordWithInverse ] );
#! @Description
#! Given a sequence of elements $V$ of a free group, returns a Nielsen reduced set $W$ that is equivalent to $V$.
#! @Arguments V.
DeclareGlobalFunction( "NielsenReducedSet" );
#! @Description
#! Given a sequence of elements $V$ of a free group, returns whether $V$ is a Nielsen reduced set or not.
#! @Arguments V.
DeclareGlobalFunction( "IsNielsenReducedSet" );
#! @Description
#! Given a sequence of elements $V$ of a free group and a word $w$, returns whether $w$ is in the subgroup generated by $V$ or not.
#! @Arguments V, w.
DeclareGlobalFunction( "InFreeSubgroup" );
#! @Description
#! Given two sequence of elements $V,W$ of a free group and a word $w$, returns whether the subgroup generated by $W$ is a subgroup of the group generated by $V$ or not.
#! @Arguments V, W.
DeclareGlobalFunction( "IsSubgroupOfFreeSubgroup" );
#! @Description
#! Given two sequence of elements $V,W$ of a free group and a word $w$, returns whether the subgroup generated by $W$ is a normal subgroup of the group generated by $V$ or not.
#! @Arguments V, W.
DeclareGlobalFunction( "IsNormalSubgroupOfFreeSubgroup" );
#! @Description
#! Given two sequence of elements $V,W$ of a free group and a word $w$, returns whether $V$ and $W$ are equivalent or not.
#! @Arguments V, W.
DeclareGlobalFunction( "AreEquivalent" );
